In [ ]:
!pip install pandas
!pip install requests

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.4.22)

In [ ]:
import requests
import pandas as pd
import time

In [ ]:
# Obtenemos Segovia por separado ya que el enlace es diferente
years = [2024, 2025]
meses = ["enero","febrero","marzo","abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"]
mes_dict = {"enero":1,"febrero":2,"marzo":3,"abril":4,"mayo":5,"junio":6,"julio":7,"agosto":8,"septiembre":9,"octubre":10,"noviembre":11,"diciembre":12}

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}
base_url = "https://www.tutiempo.net/estaciones/segovia/{}-{}/"

dfs = []
errors = []
for year in years:
  for mes in meses:
      url = base_url.format(mes, year)
      print(f"Descargando {url}...")

      try:
        response = requests.get(url, headers=headers)
        response.encoding = response.apparent_encoding

        tables = pd.read_html(response.text)
        df_month = tables[0]

        df_month["Mes"] = mes_dict[mes]
        df_month["Year"] = str(year)
        df_month["Provincia"] = "Segovia"

        dfs.append(df_month)

        time.sleep(2)

      except Exception as e:
        errors.append(f"Error en {year}: {mes}")


print(errors)
df_segovia = pd.concat(dfs, ignore_index=True)
df_segovia.columns = df_segovia.columns.str.strip()

In [ ]:
df_segovia["fecha"] = df_segovia["Día"].astype(str).str.zfill(2) + "/" + df_segovia["Mes"].astype(str).str.zfill(2) + "/" + df_segovia["Year"].astype(str)

In [ ]:
df_segovia

,Día,T,TM,Tm,V,VM,PP,PA,H,Mes,Year,Provincia,fecha
0,1,4.6,8.9,1.8,7.0,18.0,0.0,905.0,68,1,2024,Segovia,01/01/2024
1,2,8.5,12.4,2.8,10.8,37.8,0.0,904.3,58,1,2024,Segovia,02/01/2024
2,3,9.9,12.0,6.9,11.9,31.0,4.6,904.1,86,1,2024,Segovia,03/01/2024
3,4,7.6,10.5,6.1,8.5,22.0,5.4,899.8,87,1,2024,Segovia,04/01/2024
4,5,2.8,4.6,1.5,15.4,44.6,16.0,896.3,93,1,2024,Segovia,05/01/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,29,5.2,9.6,2.1,6.0,21.2,0.0,903.4,77,12,2025,Segovia,29/12/2025
742,30,3.3,7.1,0.1,4.8,14.4,0.0,905.1,86,12,2025,Segovia,30/12/2025
743,31,2.2,6.8,-1.0,5.3,19.4,0.0,903.3,84,12,2025,Segovia,31/12/2025
744,Medias y totales mensuales,Medias y totales mensuales,Medias y totales mensuales,Medias y totales mensuales,Medias y totales mensuales,Medias y totales mensuales,Medias y totales mensuales,Medias y totales mensuales,Medias y totales mensuales,12,2025,Segovia,Medias y totales mensuales/12/2025
745,NaN,5.4,8.7,2.8,8.3,30.5,38.0,901.3,82.1,12,2025,Segovia,nan/12/2025

In [ ]:
# Meses a scrapear
years = [2024, 2025]
provincias = [{"Ávila":"80110"},{"Burgos":"80750"},{"León":"80550"},{"Salamanca":"82020"}, {"Soria":"81480"}, {"Valladolid":"81410"}, {"Zamora":"81300"}]
# Ávila, Burgos, León, Salamanca, Soria, Valladolid, Zamora

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}
base_url = "https://www.tutiempo.net/clima/{}/ws-{}.html"

dfs = []
errors = []
for year in years:
  months = [f"{month:02d}-{year}" for month in range(1, 13)]
  for provincia in provincias:
    for clave, valor in provincia.items():
      for month in months:
          url = base_url.format(month, valor)
          print(f"Descargando {url}...")

          try:
            response = requests.get(url, headers=headers)
            response.encoding = response.apparent_encoding

            tables = pd.read_html(response.text)
            df_month = tables[0]

            df_month["Mes"] = int(month.split('-')[0])
            df_month["Year"] = year
            df_month["Provincia"] = clave

            dfs.append(df_month)

            time.sleep(2)

          except Exception as e:
            errors.append(f"Error en {clave}: {month} - {year}")


print(errors)
# Unir todos los meses
final_df = pd.concat(dfs, ignore_index=True)
final_df.columns = final_df.columns.str.strip()

In [ ]:
errors

['Error en Ávila: 09-2025 - 2025',
 'Error en Ávila: 10-2025 - 2025',
 'Error en Ávila: 11-2025 - 2025',
 'Error en Ávila: 12-2025 - 2025',
 'Error en Burgos: 09-2025 - 2025',
 'Error en Burgos: 10-2025 - 2025',
 'Error en Burgos: 11-2025 - 2025',
 'Error en Burgos: 12-2025 - 2025',
 'Error en León: 09-2025 - 2025',
 'Error en León: 10-2025 - 2025',
 'Error en León: 11-2025 - 2025',
 'Error en León: 12-2025 - 2025',
 'Error en Salamanca: 09-2025 - 2025',
 'Error en Salamanca: 10-2025 - 2025',
 'Error en Salamanca: 11-2025 - 2025',
 'Error en Salamanca: 12-2025 - 2025',
 'Error en Soria: 09-2025 - 2025',
 'Error en Soria: 10-2025 - 2025',
 'Error en Soria: 11-2025 - 2025',
 'Error en Soria: 12-2025 - 2025',
 'Error en Valladolid: 09-2025 - 2025',
 'Error en Valladolid: 10-2025 - 2025',
 'Error en Valladolid: 11-2025 - 2025',
 'Error en Valladolid: 12-2025 - 2025',
 'Error en Zamora: 09-2025 - 2025',
 'Error en Zamora: 10-2025 - 2025',
 'Error en Zamora: 11-2025 - 2025',
 'Error en Zamora: 12-2025 - 2025']

In [ ]:
final_df["fecha"] = final_df["Día"].astype(str).str.zfill(2) + "/" + final_df["Mes"].astype(str).str.zfill(2) + "/" + final_df["Year"].astype(str)

In [ ]:
final_df

,Día,T,TM,Tm,SLP,H,PP,VV,V,VM,VG,RA,SN,TS,FG,Mes,Year,Provincia,Provincia_valor,fecha
0,1,12.2,15,9.1,-,52,0,10,13.9,25.9,-,o,NaN,NaN,NaN,1,2024,Ávila,80110,01/01/2024
1,2,15.6,21,11.9,-,59,0,9,17.6,48.2,72.2,o,NaN,NaN,NaN,1,2024,Ávila,80110,02/01/2024
2,3,13.9,15.1,12.8,-,64,10.41,10,19.3,35.2,-,NaN,NaN,NaN,NaN,1,2024,Ávila,80110,03/01/2024
3,4,10.6,13,8,-,68,0,10,17,35.2,50,o,NaN,NaN,NaN,1,2024,Ávila,80110,04/01/2024
4,5,8,10.2,6,-,83,6.1,8.7,17,25.9,53.5,o,NaN,NaN,NaN,1,2024,Ávila,80110,05/01/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4538,29,-,-,-,-,-,-,-,-,-,-,-,-,-,-,8,2025,Zamora,81300,29/08/2025
4539,30,-,-,-,-,-,-,-,-,-,-,-,-,-,-,8,2025,Zamora,81300,30/08/2025
4540,31,-,-,-,-,-,-,-,-,-,-,-,-,-,-,8,2025,Zamora,81300,31/08/2025
4541,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,8,2025,Zamora,81300,Medias y totales mensuales:/08/2025
4542,NaN,26.6,36.5,17.8,1014.6,35.5,2.54,19.4,6.6,12.6,NaN,3,0,0,0,8,2025,Zamora,81300,nan/08/2025

In [ ]:
# Estos registros son la media de cada mes, no nos valen, los borramos porque traen nulo el campo Día
df_segovia = df_segovia.dropna(subset=['Día'])
final_df = final_df.dropna(subset=['Día'])

In [ ]:
cols_df1 = set(df_segovia.columns)
cols_df2 = set(final_df.columns)

solo_en_df1 = cols_df1 - cols_df2
solo_en_df2 = cols_df2 - cols_df1

print(solo_en_df1)
print(solo_en_df2)

set()
set()

In [ ]:
df_segovia.drop(columns=['PA'], inplace=True)
final_df.drop(columns=['SN','TS','RA','VV','FG','VG','Provincia_valor','SLP'], inplace=True)

In [ ]:
df_total = pd.concat([df_segovia, final_df], ignore_index=True)

In [ ]:
df_total

,Día,T,TM,Tm,V,VM,PP,H,Mes,Year,Provincia,fecha
0,1,4.6,8.9,1.8,7.0,18.0,0.0,68,1,2024,Segovia,01/01/2024
1,2,8.5,12.4,2.8,10.8,37.8,0.0,58,1,2024,Segovia,02/01/2024
2,3,9.9,12.0,6.9,11.9,31.0,4.6,86,1,2024,Segovia,03/01/2024
3,4,7.6,10.5,6.1,8.5,22.0,5.4,87,1,2024,Segovia,04/01/2024
4,5,2.8,4.6,1.5,15.4,44.6,16.0,93,1,2024,Segovia,05/01/2024
...,...,...,...,...,...,...,...,...,...,...,...,...
5121,28,-,-,-,-,-,-,-,8,2025,Zamora,28/08/2025
5122,29,-,-,-,-,-,-,-,8,2025,Zamora,29/08/2025
5123,30,-,-,-,-,-,-,-,8,2025,Zamora,30/08/2025
5124,31,-,-,-,-,-,-,-,8,2025,Zamora,31/08/2025
5125,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,Medias y totales mensuales:,8,2025,Zamora,Medias y totales mensuales:/08/2025

In [ ]:
df_total = df_total[df_total['Día'] != 'Medias y totales mensuales:']
df_total = df_total[df_total['Día'] != 'Medias y totales mensuales']

In [ ]:
df_total.replace('-', 0, inplace=True)

In [ ]:
df_total.to_excel("df_limpio.xlsx", index=False)